### PR TITLE
[WIP] Group constraints

### PR DESCRIPTION
**Pull request by sharkiteuthis**
So far just adding a groups file and parsing it, not implementing constraints

### CODE REVIEW

**Comment by sharkiteuthis** [comment]
@BenBrostoff  this is still a WIP, but I generalized groups into Rules that are contained within an (iterable) RuleSet object. Next thing on my list is to write the code to check for certain rule conflicts up front, then write tests.

Actually implementing the rules as constraints is going to run into conflicts with the pip module work you're doing for sure, so I'll take a look at that tomorrow.

**Comment by BenBrostoff** [comment]
@sharkiteuthis Going to work on the pip module over the weekend and hopefully it can get merged it by Sunday 👍

**Comment by sharkiteuthis** [comment]
@BenBrostoff I'm going to pull your pip branch tonight and start merging this stuff into that branch instead, as well as refactoring everything into Rules and Rulesets.

**Comment by BenBrostoff** [comment]
FYI if you pick this up this weekend, I hate formatting stuff so I've just starting using `autopep8`. Once you have it globally:

```
autopep8 --in-place --aggressive ./draftfast/**/*.py
```

**Pull request closed without merging**
